# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PersonalFinanceAssistant' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyJSON', '3.1.4'
  pod 'Charts', '3.0.3'

  # Pods for PersonalFinanceAssistant

  target 'PersonalFinanceAssistant-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  end

  target 'PersonalFinanceAssistantTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
