# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoneyTracker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyJSON', '3.1.4'
  pod 'Charts', '3.0.3'

  # Pods for MoneyTracker

  target 'MoneyTracker-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

    pod 'ReactNativeExceptionHandler', :path => '../node_modules/react-native-exception-handler'

  end

  target 'MoneyTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
